### PR TITLE
Adding image accessibility

### PR DESCRIPTION
**Pull request by lduarte1991**
This is quite a hefty PR. 
1. This has a way to make annotations via keyboard input in images.
2. It redoes some of the graphics. Adds a navigation bar to go from page to page that remains fixed on the screen, provides a home button for Admins (and I believe ATG students... @arthurian would love if you could check this) to head back to the hub. And pulls the fullscreen button and keyboard input button up to the top for easy access (especially when using a screen reader or the accessibility web rotor on a Mac). 
3. It adds aria-labels that are much more easily understood (had a meeting with our Accessibility guy who had quite a lot of suggestions/input). 
4. There was a debug_printer reference in target_object_database that was not pointing to utils thus it threw an error when trying to edit a target object.
5. Hides content of main sidebar when modal view pops up so that screen reader users are not given items which should be hidden to them and everyone else.
6. Started cleaning up detail.html, there is now an annotation_base.html which will handle loading everything for both text and image and will also make a lot of the accessibility stuff be consistent between the two. 
7. Made the change ChinaX wanted for the message when instructor forgets to put object_id/collection_id. This is mainly due to the fact that in edX, studio did not save any of their object_ids and collectio_ids due to a CMS problem...and every single instance had that message pop up during the release this week (Tues/Wed).

### CODE REVIEW

**Comment by arthurian** [comment]
@lduarte1991 I intend to look at the PR this afternoon and get this turned around for you.

**Comment by lduarte1991** [comment]
@arthurian You're the best! Thanks!

**Comment by arthurian** [comment]
@lduarte1991 I can confirm that the navigation bar is available to students as well as instructors in Canvas. Now it's much more obvious how to home and navigate between pages and I like that the keyboard icon is up top now. We just had some feedback about that at our workshop today.

The refactored *detail.html* -> *annotation_base.html* is great. Much more consistent now for accessibility and other things.

As far as the image annotation accessibility, it's not clear to me how I can create an image annotation using the keyboard. There doesn't appear to be a keyboard icon in the top nav bar to trigger that in the same there's one for text assignments. What am I missing?

**Comment by lduarte1991** [comment]
@arthurian Oh, I know what's going on. It is a dumb css bug for when you only have one image in an assignment. Will fix that in a second and push a commit. My bad!

**Comment by arthurian** [comment]
@lduarte1991 Awesome, thanks!

**Comment by lduarte1991** [comment]
@arthurian try it now?

**Comment by arthurian** [comment]
@lduarte1991 That fixed the issue and I played around with the keyboard input to make annotations (without screen reader).

Overall, PR looks good to me. I didn't review the PR line by line since it's pretty hefty, but mostly just skimmed for any potential issues with the functionality and also tested it in our dev environment. If there's anything in particular you wanted me to focus on code-wise, let me know.

 :+1: :+1:

**Comment by lduarte1991** [comment]
Nothing in particular. The nav bar is the only one that should have some code changes between ATG/HX  other than that it's mostly been restructuring text's detail.html and and the image stuff. cool. will merge then!

**Pull request merged**
