### PR TITLE
Cookieless Sessions

### PR DESCRIPTION
**Pull request by lduarte1991**
Sets up middleware to catch and create sessions when user has cookies turned off. It also does IP matching to limit the security vulnerabilities.

@arthurian I don't know if this was an issue in with you guys but we had a constant issue within HarvardX that users would not be able to view the tool because their browser would a) not allow third-party cookies or data to be saved or b) Safari settings will only save cookies of sites visited (and since our server is on a different domain than edX we were not on their list). 

So below you should see that the session_key is passed now when they first initialize the tool. It is normally saved in a cookie with the actual session data stored server-side. Then the key is passed in via the url as a parameter. A middleware detects whether the cookie exists. If it doesn't it will look for the session's name in the parameter and creates the session for the page loaded. 

IP matching checks to make sure that their IP address matches the session's last IP address. If it doesn't then it rejects it and sends a 500 Error. 

Thoughts on this? Or anything wrong/stupid that sticks out for you?

I won't merge this yet since there are a couple of small things I want to fix, but wanted to get this up for your eyes asap.

### CODE REVIEW

**Comment by arthurian** [comment]
@lduarte1991 Nothing sticks out to me based on a first pass of the code. I'll throw this up in our dev environment next week for more testing and let you know if I see any issues there.

**Comment by lduarte1991** [comment]
@arthurian Don't know if this is worth your time looking into it since your parent window and lti iframe are both coming from harvard.edu servers. We are running into this issue because we have a harvard.edu for the tool serving to edx.org. 

If you think this is worth your time looking into, I suggest you take a look at the Admin panel since I didn't spend much time there because we are making the assumption that the instructor has their cookies turned on so as not to pass around their session key. 

If you think it's not worth your time since it won't be an issue for y'all, I'll handle the above if/when we decide to allow students into the admin hub. 

In either case, let me know and I can merge. As always feel free to comment if you see something dumb.  Thanks!

**Comment by lduarte1991** [comment]
I should also give credit to [DCE as they provided the inspiration for this](https://github.com/harvard-dce/dce_lti/blob/master/lib/dce_lti/middleware/cookieless_sessions.rb), though I did it a bit differently. Figured it might help you decide if there was something they did I missed or got wrong.

**Comment by lduarte1991** [comment]
One last issue from this that I'll probably resolve as an extra commit in [PR-80](https://github.com/lduarte1991/hxat/pull/80) instead of here might be to figure out how to get this to work with Mirador since it handles the api from its end. I want to talk to Rashmi first and figure out if this is where I'd have to diverge from her code, ask her to make a change to help do this, or something else entirely.

**Pull request merged**
