### PR TITLE
Mirador v2.1.2

### PR DESCRIPTION
**Pull request by lduarte1991**
Worked with Rashmi to bring Mirador up to their latest version (v.2.1.2) which involved quite a few changes code-wise including an "event emitter" and changes to the UI/UX involving circle-shaped annotations, free-form shaped annotations, line-shaped annotations, and point-shaped annotaitons. The rangePosition component of the new annotations are now done in SVG with path data inside instead of the bounds for the full image. Thumbnails now will have an svg overlay to redraw the shapes within the square bounds of the image. 

The only issue deals with a bug in the way it handles annotations made by keyboard-input only. For some reason the math used to calculate the bounds to SVG are off and it selects more of the area than the user intended. It's not a dealbreaker, but also not desired. Thoughts on whether we should wait until the Mirador team fixes that bug before merging or make that a separate PR once they're done (don't know if this is high or low on their priority list and when it could get done), @arthurian ?

### CODE REVIEW

**Comment by lduarte1991** [comment]
@arthurian In case it makes life easier, I've made a branch with all three awaiting PRs [here](https://github.com/lduarte1991/hxat/tree/release-2017-03-15) since there were a few conflicts. We might be pushing it to our live instance soon. But will wait your thoughts before merging to master.

**Comment by arthurian** [comment]
@lduarte1991 Thanks, yeah that's a great idea. I'm looking at the branch, and if you don't mind, I'm going to turn it into its own consolidated PR.

**Comment by arthurian** [comment]
@lduarte1991 On the issue you mentioned regarding annotations created by keyboard input, is there a report of this issue on the [list of mirador issues](https://github.com/mirador/mirador/issues) that we can keep tabs on, or perhaps contribute to?

From my point of view, it would be worth upgrading to the latest version of Mirador and then doing a follow-up PR to fix the keyboard input issue as soon as a fix is available. I would only want to move forward with the upgrade, however, if a bug report has actually been filed with the Mirador project.

**Comment by lduarte1991** [comment]
@arthurian Just talked to Rashmi about this. It appears they've recently fixed this and will be in their 2.1.3 release scheduled in a week or two. I'll post more info when I get more.

**Pull request merged**
