### PR TITLE
Annotation Permissions

### PR DESCRIPTION
**Pull request by arthurian**
@lduarte1991 This PR enables *view permissions* for ATG in conjunction with [CATCH v0.5.12](https://github.com/annotationsatharvard/catcha/releases/tag/v0.5.12). It's more or less the same as https://github.com/Harvard-ATG/annotationsx/pull/58 with one or two additional commits to fix bugs.

Take a look and let me know if there's anything that gives you pause or if you test it and find any issues.

### CODE REVIEW

**Comment by lduarte1991** [comment]
I've been playing around with this for a bit. I haven't noticed any issues in my dev instance. I can't actually check the work you've done on your end because changing the ORG is only one of the things I need to do to make it work (I also need to set other options in secure.py that I don't know what they should be) so I'm going to call this a success considering it didn't affect any of the stuff I was actually doing haha. I'll take a few more days to work on it before I merge. I'll merge it in but might have to revert if I notice anything off during more testing. :+1:

**Comment by arthurian** [comment]
@lduarte1991 That's a good point. Maybe instead of using `settings.ORGANIZATION` to guard the functionality, we should create a separate setting to enable/disable the permissions, that way you can more easily test it. But yeah, if you notice any problems, definitely let me know.

**Comment by lduarte1991** [comment]
ok i'll do that in my local version. or actually...i'm just an idiot i could change it from ATG to Harvardx in my version haha. i'll look it over again later.

**Comment by lduarte1991** [comment]
@arthurian Just checked this out and got it to work. Looks good to me! :+1:

**Pull request merged**
